### ISSUE TITLE
Icons are disapearing

### ISSUE THREAD

**Issue by BENZIN69** [andrzejkupczyk/mantisbt-todolists#31] opened 2022-03-25 08:26 UTC
Hello dear !

thank you very much for your plugin it is very very useful !

there is something weird when i'm using it with an other plugin : BBCode+ 2.1.19

as soon as I activate the Todolist plugin, the BBCOde+ plugin icons disappear

![chrome_UGFbKwUTH5](https://user-images.githubusercontent.com/102351786/160082589-45df09e5-a1d9-4dfc-b69d-82aea7ad3116.png)
![chrome_COppR4PPTf](https://user-images.githubusercontent.com/102351786/160082767-6522c17f-a91f-4fdd-8590-3a350448fc1d.png)

i'm working on mantis 2.17.0

Maybe you will be able to fix something.

Thank you again for your work !

David

**Comment by andrzejkupczyk** [comment] 2022-03-25 08:30
I'm glad it comes in handy 🙂 I'll look into it.

**Comment by andrzejkupczyk** [comment] 2022-03-26 08:38
@BENZIN69 , I'm afraid I can't reproduce this problem. I tried to install BBCode+ plugin before ToDoLists plugin and vice versa, but both plugins work fine in either case. Without additional details, I will not be able to help.

Maybe you could check the browser's dev console for errors?

**Comment by BENZIN69** [comment] 2022-03-28 14:54
@andrzejkupczyk Thank you very much for taking time to check it ! i'll try to grab more informations and i'll do more tests. If i find something i'll tell you. 

Thank you again for your amazing job and your time

**Comment by andrzejkupczyk** [comment] 2022-08-05 07:33
For now, I am closing this issue due to the latest release.

**Closed by andrzejkupczyk** 2022-08-05 07:33 UTC
Labels: bug, help wanted
